MathJax.Hub.Config({
	jax: ["input/TeX","output/HTML-CSS"],
  extensions: ["tex2jax.js","MathMenu.js","MathZoom.js"],
  tex2jax: 
		{
			inlineMath: [ ['$','$'] ],
			displayMath: [ ['$$','$$'] ],
			processEscapes: true
		},
	TeX:
		{ 
			equationNumbers: { autoNumber: "AMS" },
  		Macros:
  			{
                A: ['\\forall'],
                C: ['\\mathcal{C}'],
                E: ['\\exists'],
                F: ['\\mathcal{F}'],
                e: ['\\varepsilon'],
                m: ['\\mathfrak{m}'],
                Om: ['\\Omega'],
                CC: ['\\mathbb{C}'],
                EE: ['\\mathbb{E}'],
                FF: ['\\mathbb{F}'],
                GG: ['\\mathbb{G}'],
                HH: ['\\mathbb{H}'],
                KK: ['\\mathbb{K}'],
                NN: ['\\mathbb{N}'],
                QQ: ['\\mathbb{Q}'],
                RR: ['\\mathbb{R}'],
                ZZ: ['\\mathbb{Z}'],
                op: ['\\mathrm{op}'],
                id: ['\\mathrm{id}'],
                ob: ['\\mathrm{ob}'],
                dom: ['\\mathrm{dom}'],
                cod: ['\\mathrm{cod}'],
                mor: ['\\mathrm{mor}'],
                Mor: ['\\mathrm{Mor}'],
                Map: ['\\mathrm{Map}'],
                Hom: ['\\mathrm{Hom}'],
                Iso: ['\\mathrm{Iso}'],
                End: ['\\mathrm{End}'],
                Fun: ['\\mathrm{Fun}'],
                fib: ['\\mathrm{fib}'],
                cofib: ['\\mathrm{cofib}'],
                colim: ['\\mathrm{colim}'],
                hofib: ['\\mathrm{hofib}'],
                hocofib: ['\\mathrm{hocofib}'],
                hocolim: ['\\mathrm{hocolim}'],
                Ho: ['\\mathrm{Ho}'],
                coker: ['\\mathrm{coker}'],
                span: ['\\mathrm{span}'],
                Span: ['\\mathrm{Span}'],
                tr: ['\\mathrm{tr}'],
                poly: ['\\mathrm{poly}'],
                im: ['\\mathrm{im}'],
                Ext: ['\\mathrm{Ext}'],
                Tor: ['\\mathrm{Tor}'],
                Cotor: ['\\mathrm{Cotor}'],
                Free: ['\\mathrm{Free}'],
                Frac: ['\\mathrm{Frac}'],
                Spec: ['\\mathrm{Spec}'],
                Proj: ['\\mathrm{Proj}'],
                Sq: ['\\mathrm{Sq}'],
                sing: ['\\mathrm{sing}'],
                dR: ['\\mathrm{dR}'],
                Div: ['\\mathrm{div}'],
                curl: ['\\mathrm{curl}'],
                grad: ['\\mathrm{grad}'],
                Set: ['\\mathsf{Set}'],
                Cat: ['\\mathsf{Cat}'],
                Grp: ['\\mathsf{Grp}'],
                Ab: ['\\mathsf{Ab}'],
                Vect: ['\\mathsf{Vect}'],
                Top: ['\\mathsf{Top}'],
                simto: ['\\stackrel{\\sim}{\\to}'],
                tens: ['\\otimes'],
                bigtens: ['\\bigotimes'],
                acts: ['\\curvearrowright'],
                rest: ['\\big|_{#1}', 1],
                mtx: ['\\left(\\begin{matrix} #1 \\end{matrix}\\right)', 1]
	      }
		},
	"HTML-CSS": { availableFonts: ["TeX"] }
	});
MathJax.Ajax.loadComplete("http://willperry.me/js/MathJaxLocal.js");
